apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-cronjob
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-cronjob-container
            imagePullPolicy: IfNotPresent
            image: YOUR_IMAGE_NAME
            command: ["/bin/sh"]
            args:
              - "-c"
              - "psql configdb_1 -h 127.0.0.1 -p 5433 -U configuser_1 -c \"delete from pg_ops_config_update_history where updated_at < current_date - interval '30' day;\" > /dev/null 2>&1"
          restartPolicy: OnFailure
   schedule: '*/5 * * * *' 
status: {}
